
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3307/db_microservice_loja?serverTimezone=UTC
